services:
  nextjs:
    build: .
    container_name: nextjs_app
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      
nginx:
  image: runcloud/nginx-rc:latest
  ports:
      - "80:80"
      - "443:443"
  depends_on:
      - nextjs_app
  networks:
      - app_network

networks:
  app_network:
    driver: bridge