version: "3.8"
services:
  nextjs:
    build: .
    container_name: nextjs_app
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - NODE_ENV=development
